import { StatusBar as NativeStatusBar, StyleSheet } from "react-native";

export const green = "#0F6B4F",
  ink = "#17211D",
  muted = "#66716B";
export const styles = StyleSheet.create({
  authSafe: {
    flex: 1,
    backgroundColor: "#F5F4EE",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  authKeyboard: { flex: 1, width: "100%" },
  authThemeToggle: {
    position: "absolute",
    right: 18,
    top: (NativeStatusBar.currentHeight ?? 0) + 13,
    zIndex: 10,
  },
  authBlobOne: {
    position: "absolute",
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: "#DFEDB6",
    top: -125,
    right: -95,
    opacity: 0.68,
  },
  authBlobTwo: {
    position: "absolute",
    width: 170,
    height: 170,
    borderRadius: 85,
    backgroundColor: "#DCEDE5",
    bottom: -100,
    left: -75,
    opacity: 0.75,
  },
  authLoading: { color: muted, fontSize: 12, marginTop: 13, fontWeight: "700" },
  authContent: {
    flexGrow: 1,
    width: "100%",
    maxWidth: 430,
    alignSelf: "center",
    paddingHorizontal: 22,
    paddingVertical: 28,
    justifyContent: "center",
  },
  authIdentity: { alignItems: "center", justifyContent: "center" },
  authMark: {
    width: 52,
    height: 52,
    borderRadius: 15,
    backgroundColor: green,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: green,
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  authMarkText: { color: "#D9F36A", fontSize: 26, fontWeight: "900" },
  authBrand: { color: ink, fontSize: 24, fontWeight: "900", marginTop: 10 },
  authKicker: {
    color: green,
    fontSize: 7,
    letterSpacing: 1.05,
    fontWeight: "900",
    marginTop: 2,
  },
  authIntro: { marginTop: 21, alignItems: "center", paddingHorizontal: 12 },
  authTitle: {
    color: ink,
    fontSize: 25,
    lineHeight: 31,
    fontWeight: "900",
    letterSpacing: -0.4,
    textAlign: "center",
  },
  authSubtitle: {
    color: muted,
    fontSize: 11,
    lineHeight: 17,
    marginTop: 6,
    textAlign: "center",
    maxWidth: 320,
  },
  authCard: {
    width: "100%",
    alignSelf: "center",
    backgroundColor: "#FFF",
    borderRadius: 20,
    padding: 18,
    marginTop: 20,
    borderWidth: 1,
    borderColor: "#E1E6E2",
    shadowColor: ink,
    shadowOpacity: 0.07,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  authTabs: {
    height: 45,
    borderRadius: 12,
    backgroundColor: "#EEF2EF",
    padding: 4,
    flexDirection: "row",
    marginBottom: 15,
    position: "relative",
    overflow: "hidden",
  },
  authTabSlider: {
    position: "absolute",
    left: 4,
    top: 4,
    bottom: 4,
    borderRadius: 9,
    backgroundColor: "#FFF",
    shadowColor: ink,
    shadowOpacity: 0.1,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  authTab: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  authTabActive: { backgroundColor: "#FFF" },
  authTabText: { color: muted, fontSize: 11, fontWeight: "800" },
  authTabTextActive: { color: green, fontWeight: "900" },
  socialAuthIconButton: {
    width: 44,
    height: 44,
    alignSelf: "center",
    borderWidth: 1,
    borderColor: "#DDE3DF",
    borderRadius: 22,
    backgroundColor: "#FFF",
    alignItems: "center",
    justifyContent: "center",
  },
  socialAuthBelow: { alignItems: "center", gap: 7, marginTop: 13 },
  socialAuthBelowText: {
    color: muted,
    fontSize: 7,
    fontWeight: "900",
    letterSpacing: 0.6,
  },
  googleMark: { width: 22, height: 22 },
  inputLabel: {
    color: muted,
    fontSize: 8,
    letterSpacing: 1.2,
    fontWeight: "900",
    marginBottom: 6,
    marginTop: 8,
  },
  inputShell: {
    height: 49,
    borderWidth: 1,
    borderColor: "#DDE3DF",
    borderRadius: 11,
    paddingHorizontal: 12,
    backgroundColor: "#FCFDFC",
    flexDirection: "row",
    alignItems: "center",
  },
  inputGlyph: { width: 23, color: green, fontSize: 13, fontWeight: "900" },
  authInput: {
    flex: 1,
    height: 47,
    color: ink,
    fontSize: 13,
    paddingVertical: 0,
  },
  passwordToggle: {
    color: green,
    fontSize: 8,
    fontWeight: "900",
    letterSpacing: 0.6,
    paddingLeft: 8,
  },
  passwordHint: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 6,
  },
  hintCheck: { color: "#A6ADA9", fontSize: 11, fontWeight: "900" },
  hintCheckReady: { color: green },
  hintText: { color: muted, fontSize: 9 },
  authButton: {
    width: "72%",
    height: 47,
    alignSelf: "center",
    flexShrink: 0,
    borderRadius: 11,
    backgroundColor: green,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 15,
    paddingHorizontal: 16,
  },
  authButtonDisabled: { opacity: 0.45 },
  authButtonText: { color: "#FFF", fontSize: 12, fontWeight: "900" },
  authButtonArrow: {
    position: "absolute",
    right: 17,
    color: "#D9F36A",
    fontSize: 19,
    fontWeight: "700",
  },
  authTextLink: {
    color: green,
    fontSize: 10,
    fontWeight: "900",
    textAlign: "center",
    marginTop: 13,
  },
  studentChoice: {
    marginTop: 12,
    padding: 11,
    borderWidth: 1,
    borderColor: "#DDE5E0",
    borderRadius: 11,
    backgroundColor: "#F8FAF9",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  studentChoiceActive: { borderColor: green, backgroundColor: "#EEF6F1" },
  studentCheckbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#B9C5BE",
    alignItems: "center",
    justifyContent: "center",
  },
  studentCheckboxActive: { borderColor: green, backgroundColor: green },
  studentCheckboxText: { color: "#FFF", fontSize: 11, fontWeight: "900" },
  studentChoiceCopy: { flex: 1 },
  studentChoiceTitle: { color: ink, fontSize: 10, fontWeight: "900" },
  studentChoiceBody: {
    color: muted,
    fontSize: 8,
    lineHeight: 12,
    marginTop: 2,
  },
  authTrust: {
    backgroundColor: "#EEF6F1",
    borderRadius: 10,
    paddingHorizontal: 11,
    paddingVertical: 9,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 12,
  },
  authTrustIcon: {
    width: 20,
    height: 20,
    borderRadius: 10,
    textAlign: "center",
    lineHeight: 20,
    backgroundColor: "#D9F36A",
    color: green,
    fontSize: 10,
    fontWeight: "900",
  },
  authTrustText: { flex: 1, color: "#50675C", fontSize: 9, lineHeight: 14 },
  authNote: {
    color: "#7C8580",
    fontSize: 8,
    lineHeight: 13,
    textAlign: "center",
    marginTop: 14,
    paddingHorizontal: 22,
  },
  safe: {
    flex: 1,
    backgroundColor: "#FFF",
    paddingTop: NativeStatusBar.currentHeight ?? 0,
  },
  app: {
    flex: 1,
    backgroundColor: "#FFF",
    maxWidth: 500,
    width: "100%",
    alignSelf: "center",
    overflow: "hidden",
  },
  animatedScreen: { flex: 1 },
  screen: { flex: 1, backgroundColor: "#FFF" },
  homeContent: { paddingBottom: 120 },
  standardContent: { padding: 22, paddingBottom: 120 },
  pressed: { opacity: 0.72, transform: [{ scale: 0.985 }] },
  messagesInboxContent: { padding: 22, paddingBottom: 120 },
  messagesTitleRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 14,
  },
  messagesInboxIntro: {
    color: muted,
    fontSize: 10,
    lineHeight: 15,
    marginTop: 5,
  },
  inboxCount: {
    minWidth: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: green,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 9,
  },
  inboxCountText: { color: "#FFF", fontSize: 10, fontWeight: "900" },
  inboxSearch: {
    height: 48,
    borderWidth: 1,
    borderColor: "#DDE4DF",
    borderRadius: 14,
    backgroundColor: "#F7FAF8",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 13,
    gap: 9,
    marginTop: 22,
    marginBottom: 15,
  },
  inboxSearchIcon: { color: green, fontSize: 20 },
  inboxSearchInput: { flex: 1, color: ink, fontSize: 11 },
  inboxSearchClear: { color: muted, fontSize: 21 },
  inboxLoading: { paddingVertical: 60, alignItems: "center", gap: 12 },
  conversationCard: {
    borderWidth: 1,
    borderColor: "#E0E6E2",
    borderRadius: 17,
    backgroundColor: "#FFF",
    padding: 14,
    marginBottom: 11,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  conversationUnread: { borderColor: "#9FCFBB", backgroundColor: "#F7FCF9" },
  conversationAvatar: { width: 46, height: 46, borderRadius: 15 },
  conversationAvatarFallback: {
    width: 46,
    height: 46,
    borderRadius: 15,
    backgroundColor: "#DDECE4",
    alignItems: "center",
    justifyContent: "center",
  },
  conversationAvatarText: { color: green, fontSize: 14, fontWeight: "900" },
  conversationCopy: { flex: 1, minWidth: 0 },
  conversationTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  conversationName: { color: ink, fontSize: 12, fontWeight: "900", flex: 1 },
  conversationTime: { color: muted, fontSize: 7 },
  conversationOrder: {
    color: green,
    fontSize: 8,
    fontWeight: "800",
    marginTop: 4,
  },
  conversationBottom: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 7,
  },
  conversationPreview: { color: muted, fontSize: 9, flex: 1 },
  conversationPreviewUnread: { color: ink, fontWeight: "800" },
  conversationBadge: {
    minWidth: 19,
    height: 19,
    paddingHorizontal: 5,
    borderRadius: 10,
    backgroundColor: green,
    alignItems: "center",
    justifyContent: "center",
  },
  conversationBadgeText: { color: "#FFF", fontSize: 7, fontWeight: "900" },
  conversationStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 10,
  },
  conversationStatus: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 9,
    backgroundColor: "rgba(15,107,79,.09)",
  },
  conversationStatusText: {
    color: green,
    fontSize: 6,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  conversationOpen: { color: green, fontSize: 7, fontWeight: "900" },
  inboxEmpty: {
    minHeight: 430,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  conversationScreen: {
    flex: 1,
    backgroundColor: "#F7FAF8",
    paddingTop: NativeStatusBar.currentHeight ?? 0,
  },
  conversationHeader: {
    minHeight: 70,
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: "#E1E7E3",
    backgroundColor: "#FFF",
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
  },
  conversationBack: {
    width: 35,
    height: 35,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  conversationBackText: { color: ink, fontSize: 32, lineHeight: 32 },
  conversationHeaderAvatar: { width: 42, height: 42, borderRadius: 14 },
  conversationHeaderAvatarFallback: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: "#DDECE4",
    alignItems: "center",
    justifyContent: "center",
  },
  conversationHeaderName: { color: ink, fontSize: 13, fontWeight: "900" },
  conversationHeaderMeta: { color: green, fontSize: 8, marginTop: 4 },
  conversationMessageList: { flex: 1 },
  conversationMessageContent: {
    padding: 16,
    paddingBottom: 22,
    flexGrow: 1,
    justifyContent: "flex-end",
  },
  messageDateSeparator: {
    alignItems: "center",
    paddingHorizontal: 18,
    marginTop: 8,
    marginBottom: 16,
  },
  messageDateSeparatorText: {
    color: muted,
    fontSize: 9,
    fontWeight: "700",
    textAlign: "center",
  },
  conversationEmpty: {
    flex: 1,
    minHeight: 350,
    alignItems: "center",
    justifyContent: "center",
  },
  conversationComposerArea: {
    backgroundColor: "#FFF",
    borderTopWidth: 1,
    borderTopColor: "#E1E7E3",
    paddingBottom: 4,
  },
  header: {
    paddingHorizontal: 22,
    paddingVertical: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  hello: { fontSize: 9, letterSpacing: 1.6, fontWeight: "800", color: muted },
  brand: { color: ink, fontSize: 24, lineHeight: 29, fontWeight: "900" },
  brandAccent: { color: green },
  headerActions: { flexDirection: "row", gap: 10, alignItems: "center" },
  roundButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 1,
    borderColor: "#E4E8E5",
    alignItems: "center",
    justifyContent: "center",
  },
  bell: { fontSize: 18, color: ink },
  mobileNotificationBadge: {
    position: "absolute",
    right: -5,
    top: -5,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    paddingHorizontal: 4,
    backgroundColor: "#D95045",
    borderWidth: 2,
    borderColor: "#FFF",
    alignItems: "center",
    justifyContent: "center",
  },
  mobileNotificationBadgeText: {
    color: "#FFF",
    fontSize: 7,
    fontWeight: "900",
  },
  account: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "#E1EEE7",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  accountImage: { width: "100%", height: "100%" },
  accountText: { color: green, fontWeight: "900" },
  hero: {
    marginHorizontal: 15,
    padding: 24,
    paddingTop: 30,
    borderRadius: 24,
    backgroundColor: "#F4F3EC",
    overflow: "hidden",
  },
  heroCircleOne: {
    position: "absolute",
    width: 155,
    height: 155,
    borderRadius: 90,
    backgroundColor: "#E4EFC0",
    right: -55,
    top: -35,
  },
  heroCircleTwo: {
    position: "absolute",
    width: 85,
    height: 85,
    borderRadius: 50,
    backgroundColor: "#D9EAE1",
    right: 22,
    bottom: -43,
  },
  heroKicker: {
    color: green,
    fontSize: 9,
    letterSpacing: 1.3,
    fontWeight: "900",
  },
  heroTitle: {
    color: ink,
    fontSize: 30,
    lineHeight: 37,
    fontWeight: "900",
    marginTop: 10,
    maxWidth: 310,
  },
  heroBody: {
    color: muted,
    fontSize: 13,
    lineHeight: 20,
    marginTop: 10,
    maxWidth: 310,
  },
  search: {
    height: 54,
    marginTop: 22,
    borderRadius: 13,
    backgroundColor: "#FFF",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 15,
    shadowColor: ink,
    shadowOpacity: 0.08,
    shadowRadius: 15,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  searchIcon: { color: green, fontSize: 23, marginRight: 10 },
  searchInput: { flex: 1, fontSize: 13, color: ink },
  schoolSection: { marginTop: 25 },
  schoolLabel: {
    paddingHorizontal: 22,
    color: green,
    fontSize: 9,
    letterSpacing: 1.5,
    fontWeight: "900",
  },
  schoolHelp: {
    paddingHorizontal: 22,
    color: muted,
    fontSize: 11,
    marginTop: 5,
  },
  schoolChips: { paddingHorizontal: 22, paddingTop: 12, gap: 9 },
  schoolChip: {
    height: 38,
    paddingHorizontal: 15,
    borderRadius: 19,
    borderWidth: 1,
    borderColor: "#DDE4DF",
    backgroundColor: "#FFF",
    alignItems: "center",
    justifyContent: "center",
  },
  schoolChipActive: { backgroundColor: green, borderColor: green },
  schoolChipText: { color: ink, fontSize: 11, fontWeight: "800" },
  schoolChipTextActive: { color: "#FFF" },
  sectionTitleRow: {
    paddingHorizontal: 22,
    marginTop: 31,
    marginBottom: 15,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
  },
  eyebrow: { color: green, fontSize: 9, letterSpacing: 1.5, fontWeight: "900" },
  sectionTitle: {
    color: ink,
    fontSize: 21,
    lineHeight: 27,
    fontWeight: "900",
    marginTop: 5,
  },
  link: { color: green, fontSize: 12, fontWeight: "800" },
  categories: { paddingHorizontal: 22, gap: 11 },
  category: {
    width: 132,
    minHeight: 145,
    borderWidth: 1,
    borderColor: "#E3E7E4",
    borderRadius: 16,
    padding: 14,
    backgroundColor: "#FFF",
  },
  categorySelected: { borderColor: green, backgroundColor: "#F7FBF8" },
  categoryIcon: {
    width: 42,
    height: 42,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
  },
  categoryIconDark: { opacity: 0.88 },
  categoryIconText: { fontSize: 14, fontWeight: "900" },
  categoryName: { color: ink, fontSize: 13, fontWeight: "800", marginTop: 18 },
  categoryNameSelected: { color: green },
  categoryCount: { color: muted, fontSize: 10, marginTop: 4 },
  emptyCard: {
    marginHorizontal: 22,
    borderWidth: 1,
    borderColor: "#E3E7E4",
    borderRadius: 18,
    alignItems: "center",
    paddingHorizontal: 28,
    paddingVertical: 34,
    backgroundColor: "#FBFCFB",
  },
  emptyIcon: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: "#E2F0E8",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  emptyIconText: { color: green, fontSize: 25, fontWeight: "800" },
  emptyTitle: {
    color: ink,
    fontSize: 16,
    fontWeight: "900",
    textAlign: "center",
    marginTop: 12,
  },
  emptyBody: {
    color: muted,
    fontSize: 12,
    lineHeight: 18,
    textAlign: "center",
    marginTop: 7,
    maxWidth: 290,
  },
  providerButton: {
    marginTop: 21,
    borderRadius: 10,
    backgroundColor: green,
    paddingHorizontal: 18,
    height: 43,
    flexDirection: "row",
    alignItems: "center",
    gap: 13,
  },
  providerButtonText: { color: "#FFF", fontSize: 12, fontWeight: "800" },
  providerArrow: { color: "#D9F36A", fontSize: 18 },
  serviceCard: {
    marginHorizontal: 22,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "#E3E7E4",
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: "#FFF",
  },
  serviceCover: { width: "100%", height: 168, backgroundColor: "#E4ECE7" },
  serviceCoverFallback: {
    width: "100%",
    height: 130,
    backgroundColor: "#E4F0E9",
    alignItems: "center",
    justifyContent: "center",
  },
  serviceCoverFallbackText: { color: green, fontSize: 38, fontWeight: "900" },
  serviceCardBody: { padding: 17 },
  serviceCategory: {
    color: green,
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 1,
  },
  serviceTitle: {
    color: ink,
    fontSize: 16,
    fontWeight: "800",
    lineHeight: 22,
    marginTop: 8,
  },
  serviceProviderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 8,
  },
  serviceProviderAvatar: { width: 28, height: 28, borderRadius: 14 },
  serviceProviderFallback: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#DCEBE4",
    alignItems: "center",
    justifyContent: "center",
  },
  serviceProviderFallbackText: { color: green, fontSize: 9, fontWeight: "900" },
  serviceMeta: { color: muted, fontSize: 10, flex: 1 },
  serviceFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: "#EDF0EE",
    marginTop: 15,
    paddingTop: 12,
  },
  serviceRating: { color: "#D18E13", fontSize: 11, fontWeight: "800" },
  servicePrice: { color: ink, fontSize: 12, fontWeight: "900" },
  safetyCard: {
    marginHorizontal: 22,
    marginTop: 22,
    borderRadius: 15,
    padding: 17,
    backgroundColor: "#E9F3ED",
    flexDirection: "row",
    gap: 13,
  },
  safetyIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#D9F36A",
    alignItems: "center",
    justifyContent: "center",
  },
  safetyCopy: { flex: 1 },
  safetyTitle: { color: green, fontSize: 12, fontWeight: "900" },
  safetyBody: { color: "#4E665B", fontSize: 10, lineHeight: 15, marginTop: 4 },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(10,20,16,.45)",
    justifyContent: "flex-end",
  },
  bookingSheet: {
    height: "92%",
    backgroundColor: "#FFF",
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    paddingTop: 9,
    overflow: "hidden",
  },
  sheetHandle: {
    width: 42,
    height: 4,
    borderRadius: 3,
    backgroundColor: "#CCD3CF",
    alignSelf: "center",
    marginBottom: 7,
  },
  bookingHeader: {
    paddingHorizontal: 20,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#E8ECE9",
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  bookingHeaderCopy: { flex: 1 },
  bookingTitle: {
    color: ink,
    fontSize: 20,
    lineHeight: 26,
    fontWeight: "900",
    marginTop: 6,
  },
  closeButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F0F3F1",
    alignItems: "center",
    justifyContent: "center",
  },
  closeButtonText: { color: ink, fontSize: 25, lineHeight: 27 },
  bookingContent: { padding: 20, paddingBottom: 45 },
  bookingCover: {
    width: "100%",
    height: 190,
    borderRadius: 16,
    backgroundColor: "#E4ECE7",
  },
  bookingDescription: {
    color: muted,
    fontSize: 11,
    lineHeight: 18,
    marginTop: 15,
  },
  packageChoice: {
    borderWidth: 1,
    borderColor: "#DDE4DF",
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    backgroundColor: "#FFF",
  },
  packageChoiceActive: { borderColor: green, backgroundColor: "#F1F8F4" },
  packageChoiceTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  packageTier: {
    color: green,
    fontSize: 8,
    letterSpacing: 1.1,
    fontWeight: "900",
  },
  packageName: { color: ink, fontSize: 13, fontWeight: "900", marginTop: 4 },
  packagePrice: { color: green, fontSize: 16, fontWeight: "900" },
  packageDescription: {
    color: muted,
    fontSize: 10,
    lineHeight: 15,
    marginTop: 10,
  },
  packageMeta: { color: ink, fontSize: 9, fontWeight: "700", marginTop: 9 },
  requirementsInput: {
    minHeight: 125,
    borderWidth: 1,
    borderColor: "#DDE3DF",
    borderRadius: 12,
    padding: 13,
    color: ink,
    fontSize: 12,
    lineHeight: 18,
    textAlignVertical: "top",
    backgroundColor: "#FFF",
  },
  requirementsCount: {
    color: muted,
    fontSize: 8,
    textAlign: "right",
    marginTop: 6,
  },
  bookingSummary: {
    marginTop: 18,
    padding: 14,
    borderRadius: 13,
    backgroundColor: "#F2F6F3",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  summaryLabel: {
    color: muted,
    fontSize: 8,
    fontWeight: "900",
    letterSpacing: 1,
  },
  summaryHelp: { color: muted, fontSize: 8, marginTop: 4, maxWidth: 210 },
  summaryPrice: { color: green, fontSize: 20, fontWeight: "900" },
  providerNotice: {
    color: muted,
    fontSize: 9,
    textAlign: "center",
    marginTop: 10,
  },
  ordersIntro: {
    color: muted,
    fontSize: 11,
    lineHeight: 17,
    marginTop: 7,
    marginBottom: 22,
  },
  orderCard: {
    borderWidth: 1,
    borderColor: "#DFE5E1",
    borderRadius: 16,
    padding: 17,
    marginBottom: 13,
    backgroundColor: "#FFF",
  },
  orderTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  orderNumber: {
    color: muted,
    fontSize: 8,
    fontWeight: "900",
    letterSpacing: 0.7,
  },
  orderStatus: {
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 12,
    backgroundColor: "#FFF1CE",
  },
  orderStatusText: { color: "#8D690F", fontSize: 7, fontWeight: "900" },
  orderTitle: {
    color: ink,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "900",
    marginTop: 13,
  },
  orderProvider: { color: muted, fontSize: 9, marginTop: 5 },
  orderMetaRow: {
    borderTopWidth: 1,
    borderTopColor: "#E9EDEB",
    marginTop: 14,
    paddingTop: 13,
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
  },
  orderMetaLabel: {
    color: muted,
    fontSize: 7,
    fontWeight: "900",
    letterSpacing: 0.7,
  },
  orderMetaValue: {
    color: ink,
    fontSize: 9,
    fontWeight: "800",
    marginTop: 4,
    maxWidth: 105,
  },
  pageTitle: { color: ink, fontSize: 32, fontWeight: "900", marginTop: 7 },
  largeEmpty: {
    flex: 1,
    minHeight: 500,
    alignItems: "center",
    justifyContent: "center",
    paddingBottom: 70,
  },
  largeEmptyIcon: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "#E5F1EA",
    alignItems: "center",
    justifyContent: "center",
  },
  largeEmptyIconText: { color: green, fontSize: 30, fontWeight: "800" },
  primaryButton: {
    marginTop: 23,
    backgroundColor: green,
    borderRadius: 10,
    paddingHorizontal: 23,
    paddingVertical: 13,
  },
  primaryButtonText: { color: "#FFF", fontSize: 12, fontWeight: "800" },
  profileCard: {
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E3E7E4",
    borderRadius: 18,
    padding: 24,
    marginTop: 25,
  },
  profileAvatarButton: { position: "relative" },
  profileAvatar: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: "#DFEDE5",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderWidth: 2,
    borderColor: "#FFF",
  },
  profileAvatarImage: { width: "100%", height: "100%" },
  profileAvatarText: { color: green, fontSize: 18, fontWeight: "900" },
  avatarEditBadge: {
    position: "absolute",
    right: -2,
    bottom: -2,
    width: 25,
    height: 25,
    borderRadius: 13,
    backgroundColor: green,
    borderWidth: 2,
    borderColor: "#FFF",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarEditText: {
    color: "#FFF",
    fontSize: 16,
    fontWeight: "900",
    lineHeight: 18,
  },
  avatarHelp: { color: muted, fontSize: 8, marginTop: 8 },
  profileTitle: { color: ink, fontSize: 17, fontWeight: "900", marginTop: 10 },
  profileSubtitle: {
    color: muted,
    textAlign: "center",
    fontSize: 11,
    lineHeight: 17,
    marginTop: 6,
  },
  rolePill: {
    backgroundColor: "#E5F1EA",
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginTop: 11,
  },
  rolePillText: {
    color: green,
    fontSize: 8,
    fontWeight: "900",
    letterSpacing: 0.7,
  },
  completionTrack: {
    height: 7,
    width: "100%",
    backgroundColor: "#E8ECEA",
    borderRadius: 8,
    marginTop: 20,
  },
  completionFill: {
    height: 7,
    width: "20%",
    backgroundColor: green,
    borderRadius: 8,
  },
  completionText: {
    color: muted,
    fontSize: 9,
    marginTop: 7,
    alignSelf: "flex-end",
  },
  groupLabel: {
    color: muted,
    fontSize: 9,
    letterSpacing: 1.4,
    fontWeight: "900",
    marginTop: 28,
    marginBottom: 7,
  },
  settingRow: {
    minHeight: 72,
    borderBottomWidth: 1,
    borderBottomColor: "#EDF0EE",
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  settingIcon: {
    width: 40,
    height: 40,
    borderRadius: 11,
    backgroundColor: "#F0F5F2",
    alignItems: "center",
    justifyContent: "center",
  },
  settingIconText: { color: green, fontWeight: "900" },
  settingCopy: { flex: 1 },
  settingTitle: { color: ink, fontSize: 12, fontWeight: "800" },
  settingSubtitle: { color: muted, fontSize: 9, marginTop: 4 },
  chevron: { color: "#9AA29E", fontSize: 24 },
  expandPanel: {
    backgroundColor: "#F8FAF9",
    borderWidth: 1,
    borderColor: "#DDE5E0",
    borderRadius: 16,
    padding: 16,
    marginTop: 10,
    marginBottom: 6,
  },
  panelLoading: {
    color: muted,
    fontSize: 10,
    textAlign: "center",
    marginTop: 8,
  },
  panelSectionTitle: {
    color: green,
    fontSize: 9,
    letterSpacing: 1.2,
    fontWeight: "900",
    marginTop: 20,
    marginBottom: 3,
  },
  accountDetail: {
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: "#E5EAE7",
  },
  accountDetailLabel: {
    color: muted,
    fontSize: 8,
    letterSpacing: 1.1,
    fontWeight: "900",
    marginBottom: 6,
  },
  accountDetailValue: { color: ink, fontSize: 11, fontWeight: "700" },
  roleList: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  miniRolePill: {
    backgroundColor: "#E5F1EA",
    borderRadius: 10,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  miniRoleText: {
    color: green,
    fontSize: 8,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  fieldHint: { color: muted, fontSize: 8, marginTop: 6 },
  availabilityChoice: {
    marginTop: 14,
    padding: 11,
    borderWidth: 1,
    borderColor: "#DDE5E0",
    borderRadius: 11,
    backgroundColor: "#FFF",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  availabilityChoiceActive: { borderColor: green, backgroundColor: "#EEF6F1" },
  logoutButton: {
    height: 40,
    minWidth: 112,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: "#D9DFDB",
    borderRadius: 20,
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 25,
  },
  logoutText: { color: "#A33E36", fontSize: 11, fontWeight: "900" },
  clientInfoCard: {
    borderWidth: 1,
    borderColor: "#DDE6E0",
    borderRadius: 16,
    padding: 18,
    backgroundColor: "#F8FBF9",
    marginTop: 18,
  },
  profileForm: {
    borderWidth: 1,
    borderColor: "#E3E7E4",
    borderRadius: 18,
    padding: 18,
    backgroundColor: "#FBFCFB",
  },
  formTitle: { color: ink, fontSize: 16, fontWeight: "900" },
  formHelp: {
    color: muted,
    fontSize: 10,
    lineHeight: 16,
    marginTop: 5,
    marginBottom: 10,
  },
  noSchools: {
    borderRadius: 11,
    backgroundColor: "#FFF5DE",
    borderWidth: 1,
    borderColor: "#F0DDAE",
    padding: 13,
  },
  noSchoolsTitle: { color: "#86600D", fontSize: 11, fontWeight: "900" },
  noSchoolsBody: {
    color: "#7A6A48",
    fontSize: 9,
    lineHeight: 14,
    marginTop: 4,
  },
  profileSchoolChips: { gap: 8, paddingVertical: 2 },
  profileSchoolChip: {
    borderWidth: 1,
    borderColor: "#DDE3DF",
    borderRadius: 18,
    paddingHorizontal: 13,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF",
  },
  profileSchoolChipActive: { backgroundColor: green, borderColor: green },
  profileSchoolChipText: { color: ink, fontSize: 10, fontWeight: "800" },
  profileSchoolChipTextActive: { color: "#FFF" },
  profileInput: {
    height: 49,
    borderWidth: 1,
    borderColor: "#DDE3DF",
    borderRadius: 11,
    paddingHorizontal: 13,
    color: ink,
    fontSize: 12,
    backgroundColor: "#FFF",
  },
  accountPasswordShell: {
    height: 49,
    borderWidth: 1,
    borderColor: "#DDE3DF",
    borderRadius: 11,
    paddingHorizontal: 13,
    backgroundColor: "#FFF",
    flexDirection: "row",
    alignItems: "center",
  },
  accountPasswordInput: {
    flex: 1,
    height: 47,
    color: ink,
    fontSize: 12,
    paddingVertical: 0,
  },
  accountPasswordToggle: {
    color: green,
    fontSize: 8,
    fontWeight: "900",
    letterSpacing: 0.6,
    paddingLeft: 10,
  },
  bioInput: { height: 90, paddingTop: 12, textAlignVertical: "top" },
  saveProfileButton: {
    height: 49,
    borderRadius: 11,
    backgroundColor: green,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 17,
  },
  saveProfileText: { color: "#FFF", fontSize: 11, fontWeight: "900" },
  verificationCard: {
    borderWidth: 1,
    borderColor: "#DDE6E0",
    borderRadius: 18,
    padding: 18,
    backgroundColor: "#F8FBF9",
  },
  filePicker: {
    minHeight: 70,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "#B7C9BE",
    borderRadius: 12,
    backgroundColor: "#FFF",
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
  },
  filePickerIcon: {
    width: 36,
    height: 36,
    lineHeight: 36,
    textAlign: "center",
    borderRadius: 10,
    backgroundColor: "#E5F1EA",
    color: green,
    fontSize: 16,
    fontWeight: "900",
  },
  filePickerCopy: { flex: 1 },
  filePickerTitle: { color: ink, fontSize: 11, fontWeight: "900" },
  filePickerBody: { color: muted, fontSize: 9, marginTop: 4 },
  filePickerAction: { color: green, fontSize: 9, fontWeight: "900" },
  pendingNotice: {
    borderRadius: 11,
    backgroundColor: "#FFF5DE",
    borderWidth: 1,
    borderColor: "#F0DDAE",
    padding: 13,
  },
  pendingNoticeTitle: { color: "#86600D", fontSize: 11, fontWeight: "900" },
  pendingNoticeBody: {
    color: "#7A6A48",
    fontSize: 9,
    lineHeight: 14,
    marginTop: 4,
  },
  verifiedNotice: {
    borderRadius: 11,
    backgroundColor: "#E7F5EC",
    borderWidth: 1,
    borderColor: "#B9DDC6",
    padding: 13,
  },
  verifiedNoticeTitle: { color: green, fontSize: 11, fontWeight: "900" },
  verifiedNoticeBody: {
    color: "#4E665B",
    fontSize: 9,
    lineHeight: 14,
    marginTop: 4,
  },
  rejectedNotice: {
    borderRadius: 11,
    backgroundColor: "#FFF0EE",
    borderWidth: 1,
    borderColor: "#F0C6C0",
    padding: 13,
    marginTop: 10,
  },
  rejectedNoticeTitle: { color: "#A33E36", fontSize: 10, fontWeight: "900" },
  rejectedNoticeBody: {
    color: "#76504B",
    fontSize: 9,
    lineHeight: 14,
    marginTop: 4,
  },
  bottomNav: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 77,
    backgroundColor: "#FFF",
    borderTopWidth: 1,
    borderTopColor: "#E4E8E5",
    flexDirection: "row",
    paddingHorizontal: 7,
    paddingBottom: 5,
    shadowColor: ink,
    shadowOpacity: 0.07,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: -5 },
  },
  navItem: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  navPressed: { opacity: 0.58, transform: [{ scale: 0.92 }] },
  navIcon: { color: "#8A938E", fontSize: 20, fontWeight: "700" },
  navLabel: { color: "#8A938E", fontSize: 9, fontWeight: "700", marginTop: 4 },
  navActive: { color: green },
  activePip: {
    position: "absolute",
    bottom: 1,
    width: 18,
    height: 3,
    borderRadius: 2,
    backgroundColor: "#D9F36A",
  },
  themeToggle: {
    width: 62,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#E8ECE9",
    padding: 3,
    justifyContent: "center",
    position: "relative",
  },
  themeToggleActive: { backgroundColor: "#2B604D" },
  themeKnob: {
    position: "absolute",
    left: 3,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#FFF",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  themeKnobIcon: { fontSize: 15, color: "#75580B" },
  themeSun: { position: "absolute", left: 9, fontSize: 11, color: "#9A7208" },
  themeMoon: { position: "absolute", right: 9, fontSize: 14, color: "#EAF2EE" },
  openWorkspaceText: {
    color: green,
    fontSize: 9,
    fontWeight: "900",
    marginTop: 14,
    textAlign: "right",
  },
  workspaceSafe: {
    flex: 1,
    backgroundColor: "#FFF",
    paddingTop: NativeStatusBar.currentHeight ?? 0,
  },
  workspaceHeader: {
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#E5EAE7",
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  workspaceTitle: { color: ink, fontSize: 19, fontWeight: "900", marginTop: 4 },
  workspaceOrderNumber: { color: muted, fontSize: 9, marginTop: 4 },
  workspaceContent: { padding: 20, paddingBottom: 30 },
  workspaceSummary: {
    borderWidth: 1,
    borderColor: "#E0E6E2",
    borderRadius: 16,
    padding: 16,
    backgroundColor: "#F9FBFA",
  },
  workspaceSectionTitle: { color: ink, fontSize: 14, fontWeight: "900" },
  workspaceBody: { color: muted, fontSize: 11, lineHeight: 17, marginTop: 8 },
  workspaceFacts: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 14,
  },
  workspaceFact: {
    color: ink,
    fontSize: 9,
    fontWeight: "800",
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 12,
    backgroundColor: "rgba(15,107,79,.08)",
  },
  timelineCard: {
    borderWidth: 1,
    borderColor: "#E0E6E2",
    borderRadius: 16,
    padding: 16,
    backgroundColor: "#FFF",
  },
  timelineRow: { flexDirection: "row", gap: 12, minHeight: 66 },
  timelineRail: { width: 16, alignItems: "center" },
  timelineDot: {
    width: 11,
    height: 11,
    borderRadius: 6,
    backgroundColor: green,
    borderWidth: 2,
    borderColor: "#D9F36A",
  },
  timelineLine: {
    width: 1,
    flex: 1,
    backgroundColor: "#DDE4DF",
    marginVertical: 3,
  },
  timelineCopy: { flex: 1, paddingBottom: 15 },
  timelineStatus: { color: ink, fontSize: 10, fontWeight: "900" },
  timelineNote: { color: muted, fontSize: 9, lineHeight: 14, marginTop: 4 },
  timelineDate: { color: muted, fontSize: 8, marginTop: 4 },
  messageCard: {
    borderWidth: 1,
    borderColor: "#E0E6E2",
    borderRadius: 18,
    padding: 14,
    minHeight: 190,
    backgroundColor: "#F7FAF8",
    overflow: "hidden",
  },
  messageRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
    marginVertical: 6,
  },
  messageRowMine: { justifyContent: "flex-end" },
  messageBubble: {
    maxWidth: "76%",
    borderRadius: 17,
    paddingHorizontal: 13,
    paddingVertical: 10,
  },
  messageBubbleOther: {
    backgroundColor: "#FFF",
    borderWidth: 1,
    borderColor: "#E1E7E3",
    borderBottomLeftRadius: 5,
  },
  messageBubbleMine: {
    backgroundColor: green,
    borderBottomRightRadius: 5,
    shadowColor: green,
    shadowOpacity: 0.16,
    shadowRadius: 7,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  messageSender: {
    color: green,
    fontSize: 8,
    fontWeight: "900",
    marginBottom: 4,
  },
  messageSenderMine: { color: "#D9F36A" },
  messageBody: { color: ink, fontSize: 11, lineHeight: 16 },
  messageBodyMine: { color: "#FFF" },
  messageTime: { color: muted, fontSize: 7, marginTop: 5, textAlign: "right" },
  messageTimeMine: { color: "#C8DDD4" },
  messageEmpty: {
    color: muted,
    fontSize: 9,
    lineHeight: 15,
    textAlign: "center",
    marginTop: 5,
  },
  composer: {
    padding: 10,
    backgroundColor: "#FFF",
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 9,
  },
  composerInput: {
    flex: 1,
    maxHeight: 100,
    minHeight: 44,
    borderWidth: 1,
    borderColor: "#DCE3DF",
    borderRadius: 14,
    paddingHorizontal: 13,
    paddingVertical: 11,
    color: ink,
    backgroundColor: "#F8FAF9",
    fontSize: 11,
  },
  composerSend: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: green,
    alignItems: "center",
    justifyContent: "center",
  },
  composerSendText: { color: "#FFF", fontSize: 17, fontWeight: "900" },
  deliveryFileRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    paddingVertical: 9,
    borderBottomWidth: 1,
    borderBottomColor: "#E8EDE9",
  },
  deliveryFileIcon: {
    width: 35,
    height: 35,
    borderRadius: 10,
    backgroundColor: "#E5F1EA",
    alignItems: "center",
    justifyContent: "center",
  },
  clientDecisionCard: {
    borderWidth: 1,
    borderColor: "#DCE4DF",
    borderRadius: 16,
    padding: 16,
    backgroundColor: "#FFF",
  },
  acceptDeliveryButton: {
    minHeight: 46,
    borderRadius: 11,
    backgroundColor: green,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 14,
  },
  revisionInput: {
    minHeight: 92,
    borderWidth: 1,
    borderColor: "#DCE3DF",
    borderRadius: 11,
    padding: 12,
    textAlignVertical: "top",
    color: ink,
    backgroundColor: "#F8FAF9",
    fontSize: 11,
    lineHeight: 16,
    marginTop: 14,
  },
  revisionButton: {
    minHeight: 43,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: green,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 9,
  },
  revisionButtonText: { color: green, fontSize: 10, fontWeight: "900" },
  ratingRow: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 8,
    marginBottom: 5,
  },
  ratingStar: { fontSize: 31, color: "#D6DDD9" },
  ratingStarActive: { fontSize: 18, color: "#E4A719", fontWeight: "900" },
  reviewComplete: {
    borderWidth: 1,
    borderColor: "#DCE4DF",
    borderRadius: 16,
    padding: 16,
    backgroundColor: "#FFF",
    marginTop: 20,
  },
  mobileChatAttachment: {
    marginTop: 7,
    padding: 9,
    borderWidth: 1,
    borderColor: "rgba(15,107,79,.22)",
    borderRadius: 10,
    backgroundColor: "rgba(255,255,255,.12)",
  },
  mobileChatAttachmentName: { color: ink, fontSize: 9, fontWeight: "900" },
  mobileChatAttachmentMeta: { color: muted, fontSize: 7, marginTop: 4 },
  composerAttach: {
    width: 44,
    height: 44,
    borderWidth: 1,
    borderColor: "#DCE3DF",
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  composerAttachText: { color: green, fontSize: 24, lineHeight: 26 },
  composerAttachBadge: {
    position: "absolute",
    right: -5,
    top: -5,
    width: 17,
    height: 17,
    borderRadius: 9,
    backgroundColor: green,
    alignItems: "center",
    justifyContent: "center",
  },
  composerAttachBadgeText: { color: "#FFF", fontSize: 7, fontWeight: "900" },
  messageAvatar: {
    width: 29,
    height: 29,
    borderRadius: 10,
    backgroundColor: "#DDECE4",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 2,
  },
  messageAvatarMine: { backgroundColor: green },
  messageAvatarText: { color: green, fontSize: 9, fontWeight: "900" },
  messageAvatarTextMine: { color: "#FFF" },
  messageEmptyState: {
    alignItems: "center",
    paddingVertical: 28,
    paddingHorizontal: 20,
  },
  messageEmptyIcon: {
    width: 44,
    height: 44,
    borderRadius: 15,
    backgroundColor: "#E5F1EA",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 11,
  },
  messageEmptyTitle: { color: ink, fontSize: 11, fontWeight: "900" },
  composerArea: {
    backgroundColor: "#FFF",
    borderTopWidth: 1,
    borderTopColor: "#E1E6E3",
    marginHorizontal: -14,
    marginBottom: -14,
    marginTop: 10,
  },
  mobileFilePreview: {
    marginHorizontal: 10,
    marginTop: 9,
    paddingHorizontal: 11,
    paddingVertical: 8,
    borderRadius: 9,
    backgroundColor: "rgba(15,107,79,.09)",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  mobileFilePreviewText: {
    color: green,
    fontSize: 8,
    fontWeight: "800",
    flex: 1,
  },
  mobileFilePreviewClear: { color: green, fontSize: 8, fontWeight: "900" },
  mobileMessageScroll: { maxHeight: 390 },
  mobileMessageScrollContent: {
    paddingVertical: 2,
    flexGrow: 1,
    justifyContent: "flex-end",
  },
  messageAvatarImage: {
    width: 29,
    height: 29,
    borderRadius: 10,
    marginBottom: 2,
    borderWidth: 1,
    borderColor: "#DDE5E0",
  },
  messageAvatarImageMine: { borderColor: "#8ED0B7" },
  workspaceHeaderMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 5,
  },
  workspaceStatusPill: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 9,
    backgroundColor: "rgba(15,107,79,.11)",
  },
  workspaceStatusPillText: {
    color: green,
    fontSize: 6,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  workspaceCardEyebrow: {
    color: green,
    fontSize: 7,
    fontWeight: "900",
    letterSpacing: 1,
    marginBottom: 6,
  },
  workspaceProgressBanner: {
    borderWidth: 1,
    borderColor: "#D8E5DE",
    borderRadius: 16,
    padding: 14,
    backgroundColor: "#EFF7F2",
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginTop: 14,
  },
  workspaceProgressIcon: {
    width: 39,
    height: 39,
    borderRadius: 12,
    backgroundColor: green,
    alignItems: "center",
    justifyContent: "center",
  },
  workspaceProgressIconText: {
    color: "#D9F36A",
    fontSize: 16,
    fontWeight: "900",
  },
  workspaceProgressTitle: { color: ink, fontSize: 10, fontWeight: "900" },
  workspaceProgressBody: {
    color: muted,
    fontSize: 9,
    lineHeight: 14,
    marginTop: 4,
  },
  workspaceSectionHeading: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    marginTop: 3,
  },
  workspaceSectionHelp: {
    color: muted,
    fontSize: 8,
    marginTop: -3,
    marginBottom: 8,
  },
  workspaceTimelineCount: {
    minWidth: 25,
    height: 25,
    borderRadius: 13,
    backgroundColor: "rgba(15,107,79,.1)",
    color: green,
    textAlign: "center",
    textAlignVertical: "center",
    fontSize: 8,
    fontWeight: "900",
    marginBottom: 8,
  },
  providerIdentityPanel: { padding: 18 },
  providerIdentityHead: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    marginBottom: 6,
  },
  providerIdentityIcon: {
    width: 39,
    height: 39,
    borderRadius: 12,
    backgroundColor: "#E3F1E9",
    alignItems: "center",
    justifyContent: "center",
  },
  providerIdentityIconText: { color: green, fontSize: 15, fontWeight: "900" },
  notificationModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(5,14,10,.58)",
    padding: 18,
    justifyContent: "center",
  },
  mobileNotificationSheet: {
    maxHeight: "78%",
    borderRadius: 22,
    backgroundColor: "#FFF",
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#DCE3DF",
  },
  mobileNotificationHead: {
    padding: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: "#E5EAE7",
  },
  mobileNotificationTitle: {
    color: ink,
    fontSize: 18,
    fontWeight: "900",
    marginTop: 4,
  },
  mobileNotificationRow: {
    padding: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#E9EDEB",
    flexDirection: "row",
    gap: 11,
    alignItems: "flex-start",
  },
  mobileNotificationIcon: {
    width: 36,
    height: 36,
    borderRadius: 11,
    backgroundColor: "#EEF2EF",
    alignItems: "center",
    justifyContent: "center",
  },
  mobileNotificationIconUnread: { backgroundColor: "#DFF0E7" },
  mobileNotificationRowTitle: { color: ink, fontSize: 11, fontWeight: "900" },
  mobileNotificationRowBody: {
    color: muted,
    fontSize: 9,
    lineHeight: 14,
    marginTop: 3,
  },
  mobileNotificationRowTime: { color: muted, fontSize: 7, marginTop: 5 },
  mobileUnreadDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: green,
    marginTop: 4,
  },
  mobileNotificationEmpty: { padding: 38, alignItems: "center" },
  mobileMfaCard: {
    marginTop: 24,
    padding: 16,
    borderWidth: 1,
    borderColor: "#DCE5E0",
    borderRadius: 16,
    backgroundColor: "#F7FAF8",
  },
  mobileMfaHeading: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    marginBottom: 14,
  },
  mobileMfaBadge: {
    color: green,
    backgroundColor: "#DFF1E8",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontSize: 9,
    fontWeight: "900",
  },
  mobileMfaQr: {
    width: 220,
    height: 220,
    alignSelf: "center",
    borderRadius: 14,
    marginVertical: 14,
  },
  mobileMfaSecret: {
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1,
    textAlign: "center",
    marginVertical: 10,
  },
  mobileMfaInput: {
    minHeight: 48,
    borderWidth: 1,
    borderColor: "#DCE5E0",
    borderRadius: 11,
    paddingHorizontal: 14,
    color: ink,
    marginBottom: 12,
  },
  mobileRecoveryBox: {
    marginTop: 14,
    padding: 14,
    borderRadius: 13,
    backgroundColor: "#E8F4ED",
  },
  mobileRecoveryCode: {
    color: ink,
    fontSize: 13,
    fontWeight: "800",
    textAlign: "center",
    letterSpacing: 1,
    paddingVertical: 4,
  },
  mobileMfaDanger: {
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 12,
    borderWidth: 1,
    borderColor: "#B95A5A",
    borderRadius: 11,
  },
  mobileMfaDangerText: { color: "#B54747", fontSize: 10, fontWeight: "900" },
  passwordWaitingCard: {
    padding: 24,
    borderWidth: 1,
    borderColor: "#DCE5E0",
    borderRadius: 18,
    backgroundColor: "#F8FAF9",
    alignItems: "center",
  },
  passwordWaitingIcon: {
    width: 58,
    height: 58,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#DFF1E8",
    marginBottom: 16,
  },
  passwordWaitingIconText: { color: green, fontSize: 25, fontWeight: "900" },
  passwordWaitingTitle: {
    color: ink,
    fontSize: 19,
    fontWeight: "900",
    textAlign: "center",
  },
  passwordWaitingBody: {
    color: muted,
    fontSize: 10,
    lineHeight: 16,
    textAlign: "center",
    marginTop: 9,
  },
  passwordWaitingStatus: {
    width: "100%",
    minHeight: 50,
    borderRadius: 12,
    marginTop: 20,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    backgroundColor: "#EEF5F1",
  },
  passwordWaitingStatusText: { color: ink, fontSize: 10, fontWeight: "800" },
  passwordWaitingExpiry: { color: muted, fontSize: 8, marginTop: 10 },
  passwordCancelButton: {
    minHeight: 44,
    marginTop: 20,
    paddingHorizontal: 18,
    borderWidth: 1,
    borderColor: "#B85A5A",
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  passwordCancelButtonText: {
    color: "#B54747",
    fontSize: 10,
    fontWeight: "900",
  },
});

export const darkStyles = StyleSheet.create({
  surface: { backgroundColor: "#111713" },
  card: { backgroundColor: "#1C2520", borderColor: "#34423A" },
  navigation: {
    backgroundColor: "#18201C",
    borderTopColor: "#34423A",
    shadowColor: "#000",
  },
  primaryText: { color: "#F2F6F3" },
  mutedText: { color: "#AAB6AF" },
  outline: {
    borderColor: "#34423A",
    borderBottomColor: "#34423A",
    borderTopColor: "#34423A",
  },
  input: { backgroundColor: "#151D19", borderColor: "#3B4A42" },
  rolePill: { backgroundColor: "#203B30" },
  accentText: { color: "#83D6B6" },
  availabilityActive: { backgroundColor: "#203B30", borderColor: "#4D9E7C" },
  successNotice: { backgroundColor: "#203B30", borderColor: "#3C765F" },
  selectedCard: { backgroundColor: "#203129", borderColor: "#58B38D" },
  unreadCard: { backgroundColor: "#203129", borderColor: "#58B38D" },
  authBlob: { backgroundColor: "#244035", opacity: 0.45 },
});
